Use Cloudflare KV for storing & syncing pool data
pooltogether/pooltogether-api-monorepo pull request #17
Opened 2021-06-29 21:35 UTC by ddesrosier

2021-06-30 00:00 UTC, chuckbergeron commented on LICENSE_MIT
> +DEALINGS IN THE SOFTWARE.
🤔 odd

2021-06-30 00:50 UTC, chuckbergeron requested changes

2021-06-30 00:50 UTC, chuckbergeron commented on packages/api-entrypoint/package.json
> +  "private": true,
Why `private: true` ?

2021-06-30 00:50 UTC, chuckbergeron commented on packages/api-entrypoint/package.json
> +  "name": "api-yield-source-data",
What was wrong with `@pooltogether/api-entrypoint` as a name? Shouldn't we also rename the `packages/api-entrypoint` folder if we're going to rename the project?

2021-06-30 00:50 UTC, chuckbergeron commented on packages/api-runner/index.js
> +import { usePoolByAddress } from 'lib/hooks/usePool'
That's odd. It's coming from the same file `lib/hooks/usePool` but they've been split into two separate imports 😸

2021-06-30 00:50 UTC, chuckbergeron commented on packages/api-runner/lib/fetchers/getPoolChainData.js
> +      if (lootBoxes && lootBoxes.length >= 1) {
Typically we use `lootBoxes.length > 0` everywhere. Does it need to be gte 1?

2021-06-30 00:50 UTC, chuckbergeron commented on packages/api-runner/package.json
> +    "@pooltogether/current-pool-data": "3.4.21",
Have `3.4.23` above. Should make this the same I imagine.

2021-06-30 00:50 UTC, chuckbergeron commented on packages/api-yield-source-data/package.json
> +  "private": true,
Another `private: true`

2021-06-30 00:50 UTC, chuckbergeron commented on utils/getPoolsKey.js
> +export const getPoolsKey = (chainId) => `${chainId} - Pools`
If this is a cache key should we not avoid using spaces in the string?

2021-07-03 21:19 UTC, chuckbergeron commented
So something I've noticed after just checking staging right now and comparing to production:

GUSD: Staging: GUSD $392
GUSD: Prod: $236   
DIFF: 39.79%

USDT: Staging: USDT $237
USDT: Prod: $198  
DIFF: 16.45%

The GUSD numbers are really different (40%), and USDT a bit different (16%). Maybe something snuck in the code or was removed that affects them?

2021-07-04 00:07 UTC, ddesrosier commented
The aave estimates are no longer hard coded. That could be the reason for the difference

2021-07-04 01:51 UTC, chuckbergeron commented
Well that's a positive then 👍


--
Chuck Bergeron | PoolTogether
A new way to save
https://pooltogether.com
On Jul 3, 2021, 5:07 PM -0700, Dylan ***@***.***>, wrote:
> The aave estimates are no longer hard coded. That could be the reason for the difference
> —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-05 22:41 UTC, chuckbergeron approved these changes

2021-07-06 22:19 UTC, merged